### ISSUE TITLE
Consider adding filterFullWidth or replaceFullWidth methods

### ISSUE THREAD

**Issue by peter279k** [selective-php/encoding#12]
I think we can provide these methods and we can use them before encoding.

What are full width string? The related examples are as follows:

```
// This is the full width string
＋
// This is the half width string
+
```

Sometime I get the full width string from the raw data, but I don't need that.

And I have to filter them and replace them with half width string.

Here are my approaches are as follows:

- Create the mapped lists that the full width chars is mapped to half width chars.
- Using the regular expression to implement the filter/replace methods.

**Comment by peter279k** [comment]
Hi @odan, I'm confused about approach.

Should I create a new class to implement these two methods?

**Comment by odan** [comment]
Yes, I would prefer at least one new class for this purpose:

Class: `UnicodeWidthForm`
Methods:
* `encodeHalfWidthString` - Encodes a string to half width string
* `encodeFullWidthString` - Encodes a string to full width string

Optional add this method (nice to have):

* `stringWidth` - Get the visual width of a string - the number of columns required to display it

```php
stringWidth('a'); //=> 1
stringWidth('古'); //=> 2
```

Context: 

* https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms_(Unicode_block)
* https://jrgraphix.net/r/Unicode/FF00-FFEF
* https://unicode.org/charts/nameslist/n_FF00.html
* https://en.wikipedia.org/wiki/Unicode_equivalence
* https://unicode.org/faq/normalization.html

**Comment by peter279k** [comment]
Hi @odan, thank you for your reply.

It seems that the `stringWidth` behavior is equivalent to the [mb_strwidth](https://www.php.net/manual/en/function.mb-strwidth.php) function.

And I think we should add the `convertWidth` method. It's about converting the full/half width strings.

**Comment by odan** [comment]
> And I think we should add the convertWidth method. It's about converting the full/half width strings.

I think with the name `convertWidth` its not clear what kind of with you mean. Therefore, two separate methods have been proposed.

**Comment by peter279k** [comment]
Yes. That's right.

**Comment by odan** [comment]
Thanks for the PR 👍

**Comment by peter279k** [comment]
Hi @odan, I've found that some request changes that you mention are not modified by me.

Could you change/fix them?

Thanks.

**Comment by odan** [comment]
I've modified the mentioned changed.
