### ISSUE TITLE
htmlspecialchars, and htmlentities comparison

### ISSUE THREAD

**Issue by peter279k** [selective-php/encoding#9]
According to the [StackOverflow](https://stackoverflow.com/questions/46483/htmlentities-vs-htmlspecialchars) discussion, these functions are different.

>This function is identical to htmlspecialchars() in all ways, except with htmlentities(), all characters which have HTML character entity equivalents are translated into these entities.

Here is the example:

```php
    echo htmlentities('<Il était une fois un être>.');
    // Output: &lt;Il &eacute;tait une fois un &ecirc;tre&gt;.
    //                ^^^^^^^^                 ^^^^^^^

    echo htmlspecialchars('<Il était une fois un être>.');
    // Output: &lt;Il était une fois un être&gt;.
    //                ^                 ^
```

It's about the encoding behavior difference. If we want to process the special characters, using the `htmlentities` is greater than `htmlspecialchars`.

**Comment by odan** [comment]
For me the results of `htmlspecialchars` is totaly fine.

All PHP Template Engines like [Twig](https://github.com/twigphp/Twig/blob/3.x/src/Extension/CoreExtension.php#L1111), [Plates](https://github.com/thephpleague/plates/blob/master/src/Extension/RenderContext/func.php#L114), [Smarty](https://github.com/smarty-php/smarty/blob/master/libs/plugins/variablefilter.htmlspecialchars.php#L18) etc are using `htmlspecialchars` and NOT `htmlentities`, to encode entitites.

IMO the accepted SO answer is not correct (or just outdated, date is from 2008) => Today `htmlspecialchars` in combination with `ENT_QUOTES | ENT_SUBSTITUTE` is the best and most secure function for html encoding in PHP.

I have also written a blog post about this topic: https://odan.github.io/2017/01/02/how-to-use-htmlspecialchars-in-php.html

**Comment by peter279k** [comment]
Hi @odan, thank you for your reply. Ok let me organize these two function usage.

```bash
Psy Shell v0.9.9 (PHP 7.2.18-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> echo htmlspecialchars('<Il était une fois un être>.', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
&lt;Il était une fois un être&gt;.
>>> echo htmlentities('<Il était une fois un être>.', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
&lt;Il &eacute;tait une fois un &ecirc;tre&gt;.
```

And we can see that the output results are difference.

For `htmlentities` function, it will encode the special character string, and `htmlspecialchars` will be not.

If we don't want the special chars will be encoded, we can go ahead with the `htmlspecialchars` function.

**Comment by odan** [comment]
I think we keep it as it is, because `htmlspecialchars` seems to be mostly used (and best practice) for this task. It's bullet-proof with this parameters too. Thanks.
